### ISSUE TITLE
Named groups doesn't supported.

### ISSUE THREAD

**Issue by mailer** [javallone/regexper#62]
http://www.regular-expressions.info/named.html
![regexper](https://cloud.githubusercontent.com/assets/3842194/9632587/d9e97c92-5190-11e5-956c-d981f7b56764.png)

**Comment by javallone** [comment]
Named groups are not supported by JavaScript's regular expression syntax (which is the only syntax currently supported on regexper.com). Also, this project is deprecated, and is only kept for historical reference. The current version of regexper is in the regexper-static project, and work for adding support for other regular expression flavors is in javallone/regexper-static#4.
